name = "IndexedGraphs"
uuid = "8a731c18-cfb7-4915-927e-cc26b56b67cd"
authors = ["Stefano Crotti <stefano.crotti@polito.it>", "Alfredo Braunstein <alfredo.braunstein@polito.it>"]
version = "0.4.1"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TrackingHeaps = "d94bfb22-46ad-56c3-87d0-f6c298cb800e"

[compat]
Graphs = "1.4 - 1.9"
Reexport = "1"
TrackingHeaps = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
